### ISSUE TITLE
container with iam role in k8s

### ISSUE THREAD

**Issue by homiakos** [chaspy/aws-ecr-image-scan-findings-prometheus-exporter#144]
Hi, I am trying to add an exporter to the k8s cluster. Added service account with iam role and access to ecr. In metrics, only golang metrics.

In this case, the container will restart every 6-7 minutes. At the same time, the container does not write logs. Cloudtrail no hits to ecr.
At the same time, the container contains the variables aws and IMAGE.

/ $ env | grep aws
AWS_ROLE_ARN=arn:aws:iam::**********:role/k8s/monitoring-prod/ecr-exporter-prod
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token

/ $ env | grep IMAGE
IMAGE_TAGS=master

tell me which way to look? and I think it's useful to enable logs in the container

**Comment by chaspy** [comment]
Hello.

If the container got any errors, it should keep a log.
(For example, if the IAM role didn't have enough permissions and failed to get the image findings, it would throw up a log here: https://github.com/chaspy/aws-ecr-image-scan-findings-prometheus- exporter/blob/main/main.go#L80 )

If the container is started without a crash, it may take some time to get the first data.
Try shortening `AWS_API_INTERVAL`

**Comment by chaspy** [comment]
Let me close and please reopen if any
